upgrade vulnerabilities angular 1.8.3
guardian/flexible-restorer pull request #92
Opened 2023-06-01 12:26 UTC by dskamiotis

## What does this change?
Bumps AngularJS and related dependencies to 1.8.3.

As a result of amending <transclude> property in the element, this caused some styling of the buttons (particularly those with SVG's in them) to be misaligned) 
This required some further remedial work

In addition reducing noisy logging at he the start of the app that "may make things quite a lot noisier in logs (potentially contributing to a saturated server if you're sending them across the wire "

2023-06-13 09:40 UTC, rhystmills submitted a review, later dismissed
Code looks sensible. Was able to restore a piece of content in CODE, and do the other things you'd want to be able to do (see a list snapshots, view the article JSON) - so looks good to me.

2023-06-13 09:49 UTC, jonathonherbert requested changes
@dskamiotis before we merge, can I recommend turning off logging unhandled error rejections, per this [conversation on chat?](https://chat.google.com/room/AAAAUqoLvh4/YbZZD7FbMuE)

Here's an example of how to do it on [stack overflow](https://stackoverflow.com/a/41993170) – happy to pair!

2023-06-13 09:58 UTC, rhystmills commented
(Seems like I missed something important in chat, reverting approval for now)

2023-06-13 11:23 UTC, twrichards commented on public/javascripts/app/lib/btn/index.js
> +  'button': '<button class="{{className}}" ng-transclude><!-- --></button>',
is the html comment needed?

2023-06-13 11:26 UTC, dskamiotis commented
> @dskamiotis before we merge, can I recommend turning off logging unhandled error rejections, per this [conversation on chat?](https://chat.google.com/room/AAAAUqoLvh4/YbZZD7FbMuE)
> 
> Here's an example of how to do it on [stack overflow](https://stackoverflow.com/a/41993170) – happy to pair!

It appears `main.js` is the entry point for this app, hopefully this solves the over active logging on start up of app

2023-06-22 09:50 UTC, jonathonherbert approved these changes
Tested in CODE, navigating through versions and restoring them works as expected 👍

2023-06-26 10:08 UTC, merged